name: Build manifest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate manifest.json
        run: node tools/build-manifest.js
      - name: Commit manifest.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git diff --cached --quiet || git commit -m "chore: update manifest.json"
      - name: Push changes
        run: git push
